apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.servicePort }}
  selector:
    app: backend
