apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: backend-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
          env:
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_URI
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_URI: redis://redis-svc:6379
