apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: shreybatra/sample-frontend
          ports:
            - containerPort: 5175
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_URL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  BACKEND_URL: http://backend-svc:8000
