apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_URL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  BACKEND_URL: http://backend-svc:8000
