apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
  selector:
    app: redis-app
